### ISSUE TITLE
爱奇艺运行报错

### ISSUE THREAD

**Issue by luyan29** [imoki/sign_script#21]
SyntaxError:Expected ',' or '}' after property value in JSON at position 1117
at cookie_to_json (爱奇艺.js:298:15)
at execHandle (爱奇艺.js:439:19)
at 爱奇艺.js:98:7

**Comment by imoki** [comment]
ck的格式有误。
保留含有以下键的键值对，其余的删除：P00001、P00002、P00003、__dfp。

最终ck格式为：
P00001=xxxx;P00002=xxxx;P 00003=xxxx;__dfp=xxxx

重新运行脚本测试下就行了
