### ISSUE TITLE
push脚本报错咋解决

### ISSUE THREAD

**Issue by luyan29** [imoki/sign_script#44]
Error:网络请求失败：500 Internal Server Error,{"kdocs_proxy_err_msg":"hostName www.pushplus.plus not in whitelists"}

**Comment by luyan29** [comment]
TypeError:Cannot read properties of undefined (reading 'length')
at resultHandle (雨云.js:445:28)
at execHandle (雨云.js:630:9)
at 雨云.js:317:17

**Comment by imoki** [comment]
雨云本有点问题，跑不了的不用跑

**Comment by imoki** [comment]
pushplus需要实名才能用，可以换其他推送方式

**Comment by luyan29** [comment]
还有好几个脚本都这样，新的steamtool也是。这个要如何解决啊

**Comment by imoki** [comment]
用airscript 1.0
