### ISSUE TITLE
老大wps第一次用 运行update.js出错，内容如下，复制了几次代码，内容无误。

### ISSUE THREAD

**Issue by lcii** [imoki/sign_script#54]
09:29:34.303
通知
已开始执行
<system>
09:29:34.333
信息
🥚 创建主分配表
UPDATE.js:297:9
09:29:34.335
错误
TypeError:Cannot read properties of undefined (reading 'XlSheetType')
at createSheet (UPDATE.js:604:24)
at UPDATE.js:300:1

**Comment by lcii** [comment]
还有发现一个公众号好多代码，老大要不要参考，有兴趣我发给你

**Comment by imoki** [comment]
> 还有发现一个公众号好多代码，老大要不要参考，有兴趣我发给你

可以呀，我了解下

**Comment by imoki** [comment]
最新脚本已修复此类问题
